# Site settings
title: Hank Brekke
email: brekkehj@hnryjms.io
description: >
  Hank Brekke is developing a smarter world.
  I build inspiring products across a range of platforms to help others
  change the world through technology.
baseurl: ""
url: "https://hnryjms.github.io"
permalink: /:year/:month/:title/
twitter_username: hnryjms
github_username:  hnryjms
timezone: America/Chicago
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
exclude: [
    'vendor'
  ]

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: /css

# Page defaults
defaults:
  -
    scope:
      path: ""
    values:
      twitter: "@hnryjms"
  -
    scope:
      path: ""
      type: "posts"
    values:
      og_type: "article"
